
	NOLIST
; PICBASIC PRO(TM) Compiler 2.60, (c) 1998, 2009 microEngineering Labs, Inc. All Rights Reserved. 

LABEL?L macro Label
        RST?RP
    ifdef PM_USED
        LALL
Label
        XALL
    else
Label
    endif
    endm

SUB?BCB macro Bin, Cin, Bout
    if ((Bout) == (Bin))
      if ((Cin) == 1)
        CHK?RP  Bout
        decf    Bout, F
      else
        movlw   Cin
        CHK?RP  Bout
        subwf   Bout, F
      endif
    else
      if ((Cin) == 1)
        CHK?RP  Bin
        decf    Bin, W
      else
        movlw   Cin
        CHK?RP  Bin
        subwf   Bin, W
      endif
        MOVE?AB Bout
    endif
    endm

CMPF?BL macro Bin, Label
        CLRWDT?
        MOVE?BA Bin
        BIT?GOTO 1, STATUS, Z, Label
    endm

GOSUB?L macro Label
    local dlabel
    ifdef DEBUG_STACK
        CHK?RP  DEBUG_STACK
      ifdef DEBUG_STACK_ADDR
        bcf     STATUS, C
        rlf     DEBUG_STACK, W
        addlw   DEBUG_STACK_ADDR
        movwf   FSR
        movlw   low (dlabel)
        movwf   INDF
        incf    FSR, F
        movlw	high (dlabel)
        movwf   INDF
      endif
        incf    DEBUG_STACK, F
    endif
        L?CALL  Label
dlabel
    endm

GOTO?L macro Label
        L?GOTO  Label
    endm

HSERINCOUNT?C macro Cin
        MOVE?CB Cin, R4 + 1
    endm

HSERINSTR?B macro Bin
        MOVE?CW HSERIN, R8
      if (RAM_BANKS > 2)
	MOVE?CB	high (Bin), R2 + 1
      endif
        MOVE?CA	low (Bin)
        L?CALL  SERIN2STR
    endm
HSERIN_USED = 1
SERIN2STR_USED = 1

HSEROUT?C macro Cin
        movlw   Cin
        L?CALL  HSEROUT
    endm
HSEROUT_USED = 1

HSEROUTCOUNT?C macro Cin
        MOVE?CB Cin, R4 + 1
    endm

HSEROUTSTRN?B macro Bin
        MOVE?CW HSEROUTJ, R8
      if (RAM_BANKS > 2)
	MOVE?CB	high (Bin), R2 + 1
      endif
        MOVE?CA	low (Bin)
        L?CALL  SEROUT2STRN
    endm
HSEROUTJ_USED = 1
SEROUT2STRN_USED = 1

LCDOUT?C macro Cin
        movlw   Cin
        L?CALL  LCDOUT
    endm
LCDOUT_USED = 1

LCDOUTD?B macro Bin
        MOVE?BA Bin
        L?CALL  LCDOUTDEC
    endm
LCDOUTDEC_USED = 1

LCDOUTCOUNT?C macro Cin
        MOVE?CB Cin, R4 + 1
    endm

LCDOUTSTRN?B macro Bin
        MOVE?CW LCDOUTJ, R8
      if (RAM_BANKS > 2)
	MOVE?CB	high (Bin), R2 + 1
      endif
        MOVE?CA	low (Bin)
        L?CALL  SEROUT2STRN
    endm
LCDOUTJ_USED = 1
SEROUT2STRN_USED = 1

PAUSE?C macro Cin
    if (((Cin) >> 8) == 0)
        MOVE?CA Cin
        L?CALL  PAUSE
    else
        MOVE?CB (Cin) >> 8, R1 + 1
        MOVE?CA low (Cin)
        L?CALL  PAUSEL
    endif
    endm
PAUSE_USED = 1

RETURN? macro
    ifdef DEBUG_STACK
        CHK?RP  DEBUG_STACK
        decf    DEBUG_STACK, F
    endif
        RST?RP
        return
    endm


	LIST
